package com.smartmssa.bank_discount;
import com.smartmssa.bank_discount.Order,com.smartmssa.bank_discount.CrediterCompte;

rule "HDFC"
    when
        orderObject: Order(cardType=="HDFC" && price>1000)
    then
        orderObject.setDiscount(5);
end

rule "ICICI"
    when
        orderObject: Order(cardType=="ICICI" && price>15000)
    then
        orderObject.setDiscount(8);
end

rule "DBS"
    when
        orderObject: Order(cardType=="DBS" && price>15000)
    then
        orderObject.setDiscount(15);
end

rule "Crediter compte"
    when
        crediterCompteObject: CrediterCompte(operateur=="mauritel" && credit>10000)
    then
        crediterCompteObject.setTax(10);
end
