package com.smartmssa.bank_discount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CrediterCompte implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CrediterCompte() {
    }




}